# https://k9scli.io/topics/config/
k9s:
  liveViewAutoRefresh: false
  screenDumpDir: /temp/k9s
  refreshRate: 2
  maxConnRetry: 5
  readOnly: false
  noExitOnCtrlC: true
  ui:
    enableMouse: false
    headless: false
    logoless: true
    crumbsless: false
    reactive: false
    noIcons: false
    defaultsToFullScreen: false
    skin: sarge
  skipLatestRevCheck: false
  disablePodCounting: false
  shellPod:
    image: ubuntu
    namespace: default
    limits:
      cpu: 500m
      memory: 2Gi
  imageScans:
    enable: false
    exclusions:
      namespaces: ["kube-system"]
      labels: {}
  logger:
    tail: 5000
    buffer: 10000
    sinceSeconds: -1
    textWrap: true
    showTime: false
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
